spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intuitdb
    username: root
    password: root

#jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
message: catalog of all products.